### ISSUE TITLE
Unable to parse YAML configuration file

### ISSUE THREAD

**Issue by jrompkovski** [DeloitteDigitalUK/jira-agile-metrics#12]
I get a error when I run the command: 

`jira-agile-metrics config.yaml`

The YAML patterns are considered in verification.

```
Traceback (most recent call last):
  File "C:\Users\jonas.rompkovski\AppData\Local\Programs\Python\Python36\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\jonas.rompkovski\AppData\Local\Programs\Python\Python36\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\JONAS~1.ROM\OneDrive\ONEDRI~1\SASCAR\JIRAAG~1\virtual\Scripts\jira-agile-metrics.exe\__main__.py", line 9, in <module>
  File "c:\users\jonas~1.rom\onedrive\onedri~1\sascar\jiraag~1\virtual\lib\site-packages\jira_agile_metrics\cli.py", line 49, in main
    run_command_line(parser, args)
  File "c:\users\jonas~1.rom\onedrive\onedri~1\sascar\jiraag~1\virtual\lib\site-packages\jira_agile_metrics\cli.py", line 81, in run_command_line
    options = config_to_options(config.read())
  File "c:\users\jonas~1.rom\onedrive\onedri~1\sascar\jiraag~1\virtual\lib\site-packages\jira_agile_metrics\config.py", line 116, in config_to_options
    raise ConfigError("Unable to parse YAML configuration file.") from None
jira_agile_metrics.config.ConfigError: Unable to parse YAML configuration file.
```

**Comment by optilude** [comment]
There is a syntax error in your YAML file. Without seeing it it’s not possible to suggest where.
