### ISSUE TITLE
Throughput Calculation Error

### ISSUE THREAD

**Issue by Narsail** [DeloitteDigitalUK/jira-agile-metrics#30]
Hi,

i'm running into the following error. It seems that the generated image size is too big.

```
[2020-09-24 12:51:12 ERROR] Writing file for ThroughputCalculator failed with a fatal error. Attempting to run subsequent writers regardless.
Traceback (most recent call last):
  File "/Users/davidmoeller/Developer/agile_metrics/venv/lib/python3.8/site-packages/jira_agile_metrics/calculator.py", line 56, in run_calculators
    c.write()
  File "/Users/davidmoeller/Developer/agile_metrics/venv/lib/python3.8/site-packages/jira_agile_metrics/calculators/throughput.py", line 38, in write
    self.write_chart(data, self.settings['throughput_chart'])
  File "/Users/davidmoeller/Developer/agile_metrics/venv/lib/python3.8/site-packages/jira_agile_metrics/calculators/throughput.py", line 103, in write_chart
    fig.savefig(output_file, bbox_inches='tight', dpi=300)
  File "/Users/davidmoeller/Developer/agile_metrics/venv/lib/python3.8/site-packages/matplotlib/figure.py", line 2311, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/Users/davidmoeller/Developer/agile_metrics/venv/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 2210, in print_figure
    result = print_method(
  File "/Users/davidmoeller/Developer/agile_metrics/venv/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 1639, in wrapper
    return func(*args, **kwargs)
  File "/Users/davidmoeller/Developer/agile_metrics/venv/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    FigureCanvasAgg.draw(self)
  File "/Users/davidmoeller/Developer/agile_metrics/venv/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 402, in draw
    self.renderer = self.get_renderer(cleared=True)
  File "/Users/davidmoeller/Developer/agile_metrics/venv/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 418, in get_renderer
    self.renderer = RendererAgg(w, h, self.figure.dpi)
  File "/Users/davidmoeller/Developer/agile_metrics/venv/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 96, in __init__
    self._renderer = _RendererAgg(int(width), int(height), dpi)
ValueError: Image size of 15443364x1476 pixels is too large. It must be less than 2^16 in each direction.
```

Did this happen in the past? Is there an easy way of solving it?

**Comment by marco-miller** [comment]
Also getting this issue locally from my own end. Thanks for reporting it.

**Comment by Narsail** [comment]
Sry, totally missing to report that i ran it on a Mac with Catalina.

Btw in a jupyter notebook, run in a Docker container, everything is fine.

**Comment by marco-miller** [comment]
When I run using [the documented docker command](https://github.com/DeloitteDigitalUK/jira-agile-metrics#using-docker), I still get the issue. This for me happens on Ubuntu 18.04.5 LTS, same stack trace and error, python 3.8.

**Comment by miohtama** [comment]
I can repeat this as well

```
[2020-10-13 14:19:35 ERROR] Writing file for ThroughputCalculator failed with a fatal error. Attempting to run subsequent writers regardless.
Traceback (most recent call last):
  File "/Users/moo/code/jira-stats/venv/lib/python3.8/site-packages/jira_agile_metrics/calculator.py", line 56, in run_calculators
    c.write()
  File "/Users/moo/code/jira-stats/venv/lib/python3.8/site-packages/jira_agile_metrics/calculators/throughput.py", line 38, in write
    self.write_chart(data, self.settings['throughput_chart'])
  File "/Users/moo/code/jira-stats/venv/lib/python3.8/site-packages/jira_agile_metrics/calculators/throughput.py", line 103, in write_chart
    fig.savefig(output_file, bbox_inches='tight', dpi=300)
  File "/Users/moo/code/jira-stats/venv/lib/python3.8/site-packages/matplotlib/figure.py", line 2311, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/Users/moo/code/jira-stats/venv/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 2210, in print_figure
    result = print_method(
  File "/Users/moo/code/jira-stats/venv/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 1639, in wrapper
    return func(*args, **kwargs)
  File "/Users/moo/code/jira-stats/venv/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    FigureCanvasAgg.draw(self)
  File "/Users/moo/code/jira-stats/venv/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 402, in draw
    self.renderer = self.get_renderer(cleared=True)
  File "/Users/moo/code/jira-stats/venv/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 418, in get_renderer
    self.renderer = RendererAgg(w, h, self.figure.dpi)
  File "/Users/moo/code/jira-stats/venv/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 96, in __init__
    self._renderer = _RendererAgg(int(width), int(height), dpi)
ValueError: Image size of 4344593x1476 pixels is too large. It must be less than 2^16 in each direction.
```

I think it is related to the queried data and the input the diagram receives. It somehow tries to build a too big image - maybe Throughput chart has some labels, etc. causing the issue.

**Comment by miohtama** [comment]
I traced the problem of annotating throughput chart. If you remove this loop then it fixes the problem

```python
    def write_chart(self, data, output_file):
        chart_data = data.copy()

        if len(chart_data.index) == 0:
            logger.warning("Cannot draw throughput chart with no completed items")
            return

        fig, ax = plt.subplots()

        if self.settings['throughput_chart_title']:
            ax.set_title(self.settings['throughput_chart_title'])

        # Calculate zero-indexed days to allow linear regression calculation
        day_zero = chart_data.index[0]
        chart_data['day'] = (chart_data.index - day_zero).days

        # Fit a linear regression (http://stackoverflow.com/questions/29960917/timeseries-fitted-values-from-trend-python)
        fit = sm.ols(formula="count ~ day", data=chart_data).fit()
        chart_data['fitted'] = fit.predict(chart_data)

        # Plot

        ax.set_xlabel("Period starting")
        ax.set_ylabel("Number of items")

        ax.plot(chart_data.index, chart_data['count'], marker='o')
        plt.xticks(chart_data.index, [d.date().strftime('%d/%m/%Y') for d in chart_data.index], rotation=70, size='small')

        _, top = ax.get_ylim()
        ax.set_ylim(0, top + 1)

        # for x, y in zip(chart_data.index, chart_data['count']):
        #     if y == 0:
        #         continue
        #     ax.annotate(
        #         "%.0f" % y,
        #         xy=(x.toordinal(), y + 0.2),
        #         ha='center',
        #         va='bottom',
        #         fontsize="x-small",
        #     )

        ax.plot(chart_data.index, chart_data['fitted'], '--', linewidth=2)

        set_chart_style()

        # Write file
        logger.info("Writing throughput chart to %s", output_file)
        fig.savefig(output_file, bbox_inches='tight', dpi=300)
        plt.close(fig)
````

xypairs seem to have funny values when it fails:

```
(737430, 2.2)
(737437, 22.2)
(737444, 1.2)
(737451, 1.2)
(737458, 7.2)
(737479, 13.2)
(737486, 8.2)
(737493, 1.2)
(737500, 3.2)
(737507, 19.2)
(737514, 13.2)
(737521, 3.2)
(737528, 3.2)
(737542, 2.2)
```

@optilude Please advise how to fix. I am new to maplotlib.

**Comment by optilude** [comment]
Wouldn't say I'm an expert either... That loop is adding labels on the chart. I wonder if the calculation of x/y coordinates is going wrong and ending up placing the label somewhere off-grid? Not sure.

**Comment by miohtama** [comment]
@optilude Ok I will keep poking. Would it be possible for you to get a "working sample" what values need to go there? As I cannot get a good working output from my JIRA, so I do not know how to start. I will try to look from unit tests, but not sure if that data is useful as it seems to be very synthetic.

**Comment by miohtama** [comment]
I got an idea. I will try to make it do SVG output where the pixel size is matter, so I can get visual output what's wrong with the graph.

**Comment by miohtama** [comment]
As a workaround, SVG export of the image does not show anything unusual:

<img width="535" alt="image" src="https://user-images.githubusercontent.com/49922/96013709-d8eee800-0e45-11eb-87df-f97e478ed6df.png">

Just change 'throughput.png' to 'throughput.svg'

**Comment by miohtama** [comment]
I also took a dive into `get_renderer` that sets the image size in the case of a corruption:

```
    def get_renderer(self, cleared=False):
        w, h = self.figure.bbox.size
        key = w, h, self.figure.dpi
        import ipdb; ipdb.set_trace()
```
self.figure.bbox.size
array([4.08912264e+06, 1.47657266e+03])
```

```

**Comment by odyssey4me** [comment]
Yep, I'm getting this too with this data set.

```
            count  day     fitted
2020-10-05     20    0  16.952381
2020-10-12     10    7  14.038095
2020-10-19      8   14  11.123810
2020-10-26     13   21   8.209524
2020-11-02      6   28   5.295238
2020-11-09      1   35   2.380952
```

**Comment by Narsail** [comment]
Can i ask where we are with this issue? I'm not able to run
```
docker run -it --rm -v $PWD:/data optilude/jira-agile-metrics:latest engineering_delivery.yaml
```
without failing the creation of the report due to this error.

**Comment by Narsail** [comment]
I get the same error for the ProgressReportCalculator btw @odyssey4me. When I use the Progress Report Configuration.

```
[2020-12-02 10:44:41 ERROR] Writing file for ProgressReportCalculator failed with a fatal error. Attempting to run subsequent writers regardless.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/jira_agile_metrics/calculator.py", line 56, in run_calculators
    c.write()
  File "/usr/local/lib/python3.9/site-packages/jira_agile_metrics/calculators/progressreport.py", line 310, in write
    team_charts={team.name: {
  File "/usr/local/lib/python3.9/site-packages/jira_agile_metrics/calculators/progressreport.py", line 312, in <dictcomp>
    'throughput': plot_throughput(team.throughput_samples_cycle_times, date_format),
  File "/usr/local/lib/python3.9/site-packages/jira_agile_metrics/calculators/progressreport.py", line 768, in plot_throughput
    fig.savefig(buffer, format='png', bbox_inches='tight', dpi=220)
  File "/usr/local/lib/python3.9/site-packages/matplotlib/figure.py", line 2311, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2210, in print_figure
    result = print_method(
  File "/usr/local/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 1639, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    FigureCanvasAgg.draw(self)
  File "/usr/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 402, in draw
    self.renderer = self.get_renderer(cleared=True)
  File "/usr/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 418, in get_renderer
    self.renderer = RendererAgg(w, h, self.figure.dpi)
  File "/usr/local/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 96, in __init__
    self._renderer = _RendererAgg(int(width), int(height), dpi)
ValueError: Image size of 3921025x1062 pixels is too large. It must be less than 2^16 in each direction.
```

**Comment by Narsail** [comment]
I believe it is failing as well due to using the throughput calculation internally. I'm calculation the throughput of my team in the Progress Report (instead of specifying a Min/Max).

**Comment by optilude** [comment]
A general note - I have limited capacity to investigate and fix problems, so am reliant on pull requests from others. Grateful for any help, and sorry I can't make more time to respond!

**Comment by marshall-levesque-nextgen** [comment]
My team and I faced this same issue.  I think this fixes it: https://github.com/DeloitteDigitalUK/jira-agile-metrics/pull/44

**Comment by marshall-levesque-nextgen** [comment]
This is now merged and resolved.  I think we can review and close this issue @optilude & @Narsail
