### ISSUE TITLE
Error: "AttributeError: 'PropertyHolder' object has no attribute 'resolution'"

### ISSUE THREAD

**Issue by chadxz** [DeloitteDigitalUK/jira-agile-metrics#49]
<details>
  <summary>Full stack trace:</summary>

```
~/src/jira-agile-metrics $ jira-agile-metrics config.yml
Username: my_username
Password: **********
Traceback (most recent call last):
  File "/Users/cmcelligott/.pyenv/versions/3.8.5/bin/jira-agile-metrics", line 8, in <module>
    sys.exit(main())
  File "/Users/cmcelligott/.pyenv/versions/3.8.5/lib/python3.8/site-packages/jira_agile_metrics/cli.py", line 49, in main
    run_command_line(parser, args)
  File "/Users/cmcelligott/.pyenv/versions/3.8.5/lib/python3.8/site-packages/jira_agile_metrics/cli.py", line 101, in run_command_line
    run_calculators(CALCULATORS, query_manager, options['settings'])
  File "/Users/cmcelligott/.pyenv/versions/3.8.5/lib/python3.8/site-packages/jira_agile_metrics/calculator.py", line 49, in run_calculators
    results[c.__class__] = c.run()
  File "/Users/cmcelligott/.pyenv/versions/3.8.5/lib/python3.8/site-packages/jira_agile_metrics/calculators/cycletime.py", line 42, in run
    return calculate_cycle_times(
  File "/Users/cmcelligott/.pyenv/versions/3.8.5/lib/python3.8/site-packages/jira_agile_metrics/calculators/cycletime.py", line 143, in calculate_cycle_times
    'resolution': issue.fields.resolution.name if issue.fields.resolution else None,
AttributeError: 'PropertyHolder' object has no attribute 'resolution'
```
</details>

<details>
  <summary>Here's my `config.yml` file:</summary>

```
~/src/jira-agile-metrics $ cat config.yml
---
Connection:
  domain: https://my.jira.instance
Query: project=BIZ AND Sprint=1174
Workflow:
  To Do:
    - OPEN
  In Progress:
    - IN PROGRESS
  Blocked:
    - BLOCKED/AWAIT OUTSIDE ACTION
  In Review:
    - IN REVIEW
  Waiting for Deploy:
    - WAITING FOR DEPLOY
  Done:
    - CLOSED
Output:
  CFD chart: cfd.png
```
</details>

I'm using Jira Server v7.11.1. 

From inspecting the output of /rest/api/2/search, my issues don't contain the fields.resolution property. Is that something you've run into before? I'm unsure how to fix.

**Comment by digiguru** [comment]
Hi Chadxz

I have just encountered the very same issue. The team I am working with has a custom field they've created called "Resolution" - I suspect if you have a field named the same as an expected field it causes the querying to break. Can you check if you have a custom field called resolution?

**Comment by chadxzs** [comment]
Different company now so unfortunately I cannot
