### ISSUE TITLE
Cannot convert from timedelta64[ns] to timedelta64[D]

### ISSUE THREAD

**Issue by wanderleyteixeira** [DeloitteDigitalUK/jira-agile-metrics#57]
Getting this error trying to output throughput only

```
...
[2023-06-19 18:30:18 INFO] CycleTimeCalculator completed

[2023-06-19 18:30:18 INFO] CFDCalculator running...
[2023-06-19 18:30:18 INFO] CFDCalculator completed

[2023-06-19 18:30:18 INFO] ScatterplotCalculator running...
Traceback (most recent call last):
  File "/Users/ww/env/bin/jira-agile-metrics", line 8, in <module>
    sys.exit(main())
  File "/Users/ww/env/lib/python3.10/site-packages/jira_agile_metrics/cli.py", line 49, in main
    run_command_line(parser, args)
  File "/Users/ww/env/lib/python3.10/site-packages/jira_agile_metrics/cli.py", line 101, in run_command_line
    run_calculators(CALCULATORS, query_manager, options['settings'])
  File "/Users/ww/env/lib/python3.10/site-packages/jira_agile_metrics/calculator.py", line 49, in run_calculators
    results[c.__class__] = c.run()
  File "/Users/ww/env/lib/python3.10/site-packages/jira_agile_metrics/calculators/scatterplot.py", line 23, in run
    return calculate_scatterplot_data(cycle_data)
  File "/Users/ww/env/lib/python3.10/site-packages/jira_agile_metrics/calculators/scatterplot.py", line 119, in calculate_scatterplot_data
    data['cycle_time'] = data['cycle_time'].astype('timedelta64[D]')
  File "/Users/ww/env/lib/python3.10/site-packages/pandas/core/generic.py", line 6324, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File "/Users/ww/env/lib/python3.10/site-packages/pandas/core/internals/managers.py", line 451, in astype
    return self.apply(
  File "/Users/ww/env/lib/python3.10/site-packages/pandas/core/internals/managers.py", line 352, in apply
    applied = getattr(b, f)(**kwargs)
  File "/Users/ww/env/lib/python3.10/site-packages/pandas/core/internals/blocks.py", line 511, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
  File "/Users/ww/env/lib/python3.10/site-packages/pandas/core/dtypes/astype.py", line 242, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
  File "/Users/ww/env/lib/python3.10/site-packages/pandas/core/dtypes/astype.py", line 184, in astype_array
    values = values.astype(dtype, copy=copy)
  File "/Users/ww/env/lib/python3.10/site-packages/pandas/core/arrays/timedeltas.py", line 363, in astype
    raise ValueError(
ValueError: Cannot convert from timedelta64[ns] to timedelta64[D]. Supported resolutions are 's', 'ms', 'us', 'ns'
(env) 
```

Any guidance would be appreciated.

**Comment by angusdd** [comment]
We're having the same issue.

**Comment by paulera** [comment]
This merge request solves for me. To install this specific commit with `pip`:
```
pip uninstall jira-agile-metrics
pip install git+https://github.com/DeloitteDigitalUK/jira-agile-metrics.git@97a400575af173768c5a05b4868ddb60e3cfc67a
```

**Comment by wanderleyteixeira** [comment]
> This merge request solves for me. To install this specific commit with `pip`:
> 
> ```
> pip uninstall jira-agile-metrics
> pip install git+https://github.com/DeloitteDigitalUK/jira-agile-metrics.git@97a400575af173768c5a05b4868ddb60e3cfc67a
> ```

This works! Thank you.

**Comment by wanderleyteixeira** [comment]
Some deprecation / msgs

```
/Users/ww/env/lib/python3.10/site-packages/jira_agile_metrics/calculators/scatterplot.py:110: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  chart_data["cycle_time"].quantile(quantiles).iteritems()
/Users/ww/env/lib/python3.10/site-packages/jira_agile_metrics/calculators/histogram.py:115: UserWarning: 

`distplot` is a deprecated function and will be removed in seaborn v0.14.0.

Please adapt your code to use either `displot` (a figure-level function with
similar flexibility) or `histplot` (an axes-level function for histograms).

For a guide to updating your code to use the new functions, please see
https://gist.github.com/mwaskom/de44147ed2974457ad6372750bbe5751

  sns.distplot(
/Users/ww/env/lib/python3.10/site-packages/jira_agile_metrics/calculators/histogram.py:127: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for quantile, value in ct_days.quantile(quantiles).iteritems():
/Users/ww/env/lib/python3.10/site-packages/jira_agile_metrics/calculators/ageingwip.py:105: UserWarning: FixedFormatter should only be used together with FixedLocator
  ax.set_xticklabels(ax.xaxis.get_majorticklabels(), rotation=90)
/Users/ww/env/lib/python3.10/site-packages/jira_agile_metrics/calculators/forecast.py:227: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for percentile, value in finish_date_quantiles.iteritems():
(env) 

```

**Comment by marcoala** [comment]
> This merge request solves for me. To install this specific commit with `pip`:
> 
> ```
> pip uninstall jira-agile-metrics
> pip install git+https://github.com/DeloitteDigitalUK/jira-agile-metrics.git@97a400575af173768c5a05b4868ddb60e3cfc67a
> ```

Not working for me, I tried installing this version, but I get an error when installing pandas. I attempted it on both python 3.6.15 and python 3.13.1

I'm attaching the log with the error.

[install-log.txt](https://github.com/user-attachments/files/18622904/install-log.txt)
