### ISSUE TITLE
Docker OAuth requirement version conflict

### ISSUE THREAD

**Issue by pacovi** [DeloitteDigitalUK/jira-agile-metrics#8]
With a docker fresh install on windows 10, tried to do the following command as in the Readme.md
`$ docker run -it --rm -v ./data optilude/jira-agile-metrics:latest config.yml`

On the first run, after downloading end extracting, the output shows the following:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 898, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 789, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (oauthlib 3.0.0 (/usr/local/lib/python3.7/site-packages), Requirement.parse('oauthlib<3.0.0,>=2.1.0'), {'requests-oauthlib'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/jira-agile-metrics", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3126, in <module>
    @_call_aside
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3110, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3139, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 596, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 789, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (oauthlib 3.0.0 (/usr/local/lib/python3.7/site-packages), Requirement.parse('oauthlib<3.0.0,>=2.1.0'), {'requests-oauthlib'})
```

Hence, I cannot execute it using docker 😞

**Comment by optilude** [comment]
We seem to have been caught up in some version upgrades across `requests-oauthlib` and `oauthlib`. I *believe* they are fixed now and have tested the automated build on Docker hub. Thank you for reporting!
